### ISSUE TITLE
don't have passive mode when service is File，so always failed

### ISSUE THREAD

**Issue by jimmydye** [njpanderson/push#47]
- Push version: `#.#.#`
 - VS Code version: `#.#.#`
 - Have you disabled all other extensions and can replicate: [Yes|No]

**Steps to replicate:**

**Any other information?**

**Comment by njpanderson** [comment]
Not sure I understand what you mean there @jimmydye - "Passive" mode is usually a term associated with FTP. File is a straight filesystem transfer, the intricacies of which are handled by the underlying operating system.

Do you have a replicatable example I can use?

**Comment by jimmydye** [comment]
I'm english not good... so don't care
I suppose File Mode = FTP Mode? 
I need to connect FTP server，but I don't know how to connect?

**Comment by jimmydye** [comment]
And another question：
I have three servers，when I upload either，Upload queue will clear，so I can't upload another two by queue....
Upload queue really very nice but not very friendly to multiple servers

**Comment by njpanderson** [comment]
Is it possible that you're trying to use an FTP server, and not an SFTP server?

Push does not support standard FTP, only SFTP.

**Comment by jimmydye** [comment]
Now, I have three SFTP server, and when I upload either,The upload queue will be empty, so I can't upload another two server by upload queue, Can you add the option of automatically emptying the queue?

**Comment by njpanderson** [comment]
Ah, I see what you're wanting - to upload to all three servers with the same queue contents?

This is more of a deployment concern and instead of using Push for this, you might want to look into something like a deployment tool like [capistrano](https://capistranorb.com) or [ansible](https://www.ansible.com) which essentially let you deploy to multiple servers with scripts.

If you're not wanting to go down the deployment route, you could look into a local watching task provided by gulp etc which looks at a local folder in your project (for instance `./deploy` within your project) and then when detecting changes in there, uses something like `rsync` to send the files within to all three servers. Push could then use the File transfer to "upload" the files to that `./deploy` folder instead. That could get messy though, but it would work!

I could add the option to not empty the queue in Push, but my intention is to make Push as easy to use as possible, and in doing so, provide users with expected, repeatable behaviour for their actions. Having the queue be either emptied or not could create confusion in user's workflows: for instance, if they'd forgotten they left it in that mode and it started uploading all the files they'd ever edited since vscode was opened.

**Comment by jimmydye** [comment]
Thank you for your reply
Yes, I have deployment software, version control software, etc...
But I still hope them to focus on vscode
Or can you add a function/right-click menu to upload multiple opened files at a time
That's really good for me

**Comment by njpanderson** [comment]
> Or can you add a function/right-click menu to upload multiple opened files at a time

I've been wanting to do that for a while but I don't think vscode supports operations on multiple files as of yet. It will only give you the file actually clicked on, not the selection range.

It's not very well detailed in the README, but Push does have Git based uploading tools: you can upload from either the current working copy (files which have been edited but not committed) or from a single commit in Push, which might help if you want to do repeated uploads?

**Comment by jimmydye** [comment]
Thanks for your answer
If Push add the option of automatically emptying the queue, It's also good for me, just for others, I'm not sure
