### ISSUE TITLE
fileMode - Permissions Not Being Set

### ISSUE THREAD

**Issue by jimmybrancaccio** [njpanderson/push#67]
- Push version: `0.8.0`
 - VS Code version: `1.41.1`
 - Have you disabled all other extensions and can replicate: No

**Steps to replicate:**

1. Setup an SFTP location.
2. Create a PHP file, `index.php` for example.
3. Add the following fileMode settings:

``` json
"fileMode": [{
    "glob": "*.php",
    "mode": "644"
}, {
    "glob": "**/*.css",
    "mode": "644"
}, {
    "glob": "**/*.js",
    "mode": "644"
}, {
    "glob": "**/*.jpg",
    "mode": "644"
}, {
    "glob": "**/*.png",
    "mode": "644"
},{
    "glob": "**/*/",
    "mode": "755"
}]
```

Save/upload the file via Push. For me the permissions on my `php` files are 666. Actually it seems to set 666 for any files I upload.

**Any other information?**

Please let me know if you need any other information to help troubleshoot and investigate the issue!

**Comment by njpanderson** [comment]
Hey @jimmybrancaccio — Globbing has changed a little since the 0.8.0 update, as I'm using a newer version of micromatch. (See changelog). I've just tested with the following:

```
"fileMode": [{
	// Directories
	"glob": "**/*/",
	"mode": "777"
}, {
	// PHP files
	"glob": "**/*.php",
	"mode": "766"
}, {
	// CSS files
	"glob": "**/*.css",
	"mode": "744"
}, {
	// Files
	"glob": "**/*",
	"mode": "700"
}
```

And the result of `stat -c "%a %n" *` on the directories seems as expected:

```
777 subfolder
700 subfolder/another-test-file.txt
700 subfolder/IMG_0550.jpg
744 test.css
700 test-file.txt
766 test.php
```

Using your `fileMode` settings above gives me the following:

```
755 subfolder
666 subfolder/another-test-file.txt
644 subfolder/IMG_0550.jpg
644 test.css
666 test-file.txt
666 test.php
```

The one file which didn't seem to work was the PHP file, having been given the default mode of `666`. Since changing your glob from `*.php` to `**/*.php` (because the whole path is matched), the expected `644` mode was then applied to the PHP file, meaning all of the globs which matched files seemed to work.

To that end, can you:

1) Double check that it's definitely not working for everything (including the .php file), and
2) Try changing the PHP glob as per my suggestion, and see if it works better that way?

Also, keep in mind that the *first* glob to match the file being uploaded will be applied, which means you should put the most broadly matching globs at the bottom of the `fileMode` array.

I'm not around for the rest of the night but let me know how you get on and I'll try to look tomorrow. Thanks!

**Comment by jimmybrancaccio** [comment]
Hey @njpanderson! Apologies for **my** slow response. I got busy too haha Anyways, that seems to have done the trick, now my files are 644 and no more Internal Server Errors. I appreciate the quick response and help from you. Keep up the great work on this extension, I ❤️ it!

**Comment by martbean** [comment]
Thanks for this. I just had the same problem as I was using the examples on the main page. Could you update that with the new syntax please?
