### ISSUE TITLE
Push hangs after inactivity

### ISSUE THREAD

**Issue by benmaximov** [njpanderson/push#76]
- Push version: `0.8.21`
 - VS Code version: `1.46.1`
 - Have you disabled all other extensions and can replicate: [No]

**Steps to replicate:**
1. setup push with password SFTP access
2. keep alive set to 3000ms
3. inactivity period ~30 min

**Any other information?**

last debug msgs:

ProviderSFTP: "DEBUG: Parser: Verifying MAC"
ProviderSFTP: "DEBUG: Parser: IN_PACKETDATAVERIFY (Valid HMAC)"
ProviderSFTP: "DEBUG: Parser: IN_PACKETDATAAFTER, packet: REQUEST_FAILURE"
ProviderSFTP: "DEBUG: Parser: IN_PACKETBEFORE (expecting 16)"
ℹ️ SFTP client disconnected from host v5:22
ProviderSFTP: "DEBUG: Outgoing: Writing DISCONNECT (BY_APPLICATION)"
ℹ️ SFTP client disconnected from host v5:22

**Comment by njpanderson** [comment]
That may be normal behaviour — does it re-connect when you attempt to upload though?

**Comment by JimNayzium** [comment]
Are you saying "attempt to upload" meaning something different from "saving" a file and expecting it to connect and upload automatically?

What happens to me is I edit my files, and save them as I go. Then refresh the browser and see the changes. And after a few minutes the auto-upload after saving just spins and never works. So I have to close VSCODE and re-open it and it all works instantly again.

It's like there is a timeout functionality that I could change from five minutes to 45 mintues or something? 

To be clear, all my issues happen on the auto-upload on save functionality. I just would prefer that to never "timeout" type tihng. Is that possible?

**Comment by JimNayzium** [comment]
Any word on this? I will re-explain my steps to recreate.
Work in VSCODE on files. Save them. They auto-upload instantly and perfectly. Refresh Browser to preview changes. Then work in VSCODE again for maybe ten or fifteen minutes before saving again and then the upload spins forever and never connects and uploads. I must close VSCODE and re-open and then it works perfectly again. The Output says "Running 1 task in queue and never errors out. Just hangs.

And I have set the keepAlive interval to 9000 to try and get it to work since it was happening at 3000 also and no joy.

**Comment by njpanderson** [comment]
hi Jim — sorry, I've not had any time recently to look at Push in any meaningful way. It's a personal project, and I'm in the middle of a house move—we've unfortunately suffered a bereavement too. If you do however find any solution to this, I would be more than happy to review a PR if you manage to sort it.

In the meantime I'd recommend trying debug mode on the server settings and looking at the Push output panel, to see if there's any logs made by the underlying SSH package, it could just be getting disconnected by your server without realising it.

**Comment by JimNayzium** [comment]
Sorry for your loss. Sincerely. I had a recent similar thing. Also, NO WORRIES! That's why I waited a few weeks to even repost the question. Your extension is awesome even with the disconnects. VSCODE reloads instantly as an app so it's honestly not even a big thing. It's just sometimes I get annoyed my little semi-colon fix didn't actually solve my problem when I refresh the browser but then realize it is hanging! 

I will turn on DEBUG mode. I thought I had it on honestly! Good luck to you and yours and I truly appreciate this PUSH extension. It's the best solution I have found by far.
